# Generated by Django 2.1.7 on 2019-02-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
