# Generated by Django 2.1.7 on 2019-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0002_auto_20190224_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='price',
            field=models.IntegerField(),
        ),
    ]
