# Generated by Django 2.1.7 on 2019-02-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('present', '0003_auto_20190224_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('0~10', '0~10'), ('10~20', '10~20'), ('20~30', '20~30'), ('30~40', '30~40'), ('40~50', '40~50'), ('50~60', '50~60'), ('60~', '60~')], default='0~10', max_length=10)),
                ('votes', models.IntegerField(default=1)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='present.Present')),
            ],
        ),
    ]
